/**
 * Auto-generated location names from KursLog API.
 * 101 countries, 285 cities.
 */

export const COUNTRY_NAMES: Record<string, Record<string, string>> = {
  'albania': { uk: 'Албанія', ru: 'Албания', en: 'Albania' },
  'angola': { uk: 'Ангола', ru: 'Ангола', en: 'Angola' },
  'argentina': { uk: 'Аргентина', ru: 'Аргентина', en: 'Argentina' },
  'armenia': { uk: 'Вірменія', ru: 'Армения', en: 'Armenia' },
  'australia': { uk: 'Австралія', ru: 'Австралия', en: 'Australia' },
  'austria': { uk: 'Австрія', ru: 'Австрия', en: 'Austria' },
  'azerbaijan': { uk: 'Азербайджан', ru: 'Азербайджан', en: 'Azerbaijan' },
  'bahrain': { uk: 'Бахрейн', ru: 'Бахрейн', en: 'Bahrain' },
  'belgium': { uk: 'Бельгія', ru: 'Бельгия', en: 'Belgium' },
  'benin': { uk: 'Бенін', ru: 'Бенин', en: 'Benin' },
  'brazil': { uk: 'Бразилія', ru: 'Бразилия', en: 'Brazil' },
  'bulgaria': { uk: 'Болгарія', ru: 'Болгария', en: 'Bulgaria' },
  'burkina_faso': { uk: 'Буркіна-Фасо', ru: 'Буркина-Фасо', en: 'Burkina Faso' },
  'cameroon': { uk: 'Камерун', ru: 'Камерун', en: 'Cameroon' },
  'canada': { uk: 'Канада', ru: 'Канада', en: 'Canada' },
  'chile': { uk: 'Чилі', ru: 'Чили', en: 'Chile' },
  'china': { uk: 'Китай', ru: 'Китай', en: 'China' },
  'colombia': { uk: 'Колумбія', ru: 'Колумбия', en: 'Colombia' },
  'congo': { uk: 'Конго', ru: 'Конго', en: 'Congo' },
  'costa_rica': { uk: 'Коста-Рика', ru: 'Коста-Рика', en: 'Costa Rica' },
  'croatia': { uk: 'Хорватія', ru: 'Хорватия', en: 'Croatia' },
  'cyprus': { uk: 'Кіпр', ru: 'Кипр', en: 'Cyprus' },
  'czech_republic': { uk: 'Чехія', ru: 'Чехия', en: 'Czech Republic' },
  'democratic_republic_of_the_congo': { uk: 'Демократична Республіка Конго', ru: 'Демократическая Республика Конго', en: 'Democratic Republic of the Congo' },
  'denmark': { uk: 'Данія', ru: 'Дания', en: 'Denmark' },
  'dominican_republic': { uk: 'Домініканська Республіка', ru: 'Доминиканская Республика', en: 'Dominican Republic' },
  'ecuador': { uk: 'Еквадор', ru: 'Эквадор', en: 'Ecuador' },
  'egypt': { uk: 'Єгипет', ru: 'Египет', en: 'Egypt' },
  'estonia': { uk: 'Естонія', ru: 'Эстония', en: 'Estonia' },
  'ethiopia': { uk: 'Ефіопія', ru: 'Эфиопия', en: 'Ethiopia' },
  'finland': { uk: 'Фінляндія', ru: 'Финляндия', en: 'Finland' },
  'france': { uk: 'Франція', ru: 'Франция', en: 'France' },
  'gabon': { uk: 'Габон', ru: 'Габон', en: 'Gabon' },
  'gambia': { uk: 'Гамбія', ru: 'Гамбия', en: 'Gambia' },
  'georgia': { uk: 'Грузія', ru: 'Грузия', en: 'Georgia' },
  'germany': { uk: 'Німеччина', ru: 'Германия', en: 'Germany' },
  'ghana': { uk: 'Гана', ru: 'Гана', en: 'Ghana' },
  'greece': { uk: 'Греція', ru: 'Греция', en: 'Greece' },
  'guinea': { uk: 'Гвінея', ru: 'Гвинея', en: 'Guinea' },
  'hungary': { uk: 'Угорщина', ru: 'Венгрия', en: 'Hungary' },
  'india': { uk: 'Індія', ru: 'Индия', en: 'India' },
  'indonesia': { uk: 'Індонезія', ru: 'Индонезия', en: 'Indonesia' },
  'ireland': { uk: 'Ірландія', ru: 'Ирландия', en: 'Ireland' },
  'israel': { uk: 'Ізраїль', ru: 'Израиль', en: 'Israel' },
  'italy': { uk: 'Італія', ru: 'Италия', en: 'Italy' },
  'ivory_coast': { uk: 'Кот-д\'Івуар', ru: 'Кот-д\'Ивуар', en: 'Ivory Coast' },
  'japan': { uk: 'Японія', ru: 'Япония', en: 'Japan' },
  'kazakhstan': { uk: 'Казахстан', ru: 'Казахстан', en: 'Kazakhstan' },
  'kenya': { uk: 'Кенія', ru: 'Кения', en: 'Kenya' },
  'kyrgyzstan': { uk: 'Киргизстан', ru: 'Кыргызстан', en: 'Kyrgyzstan' },
  'latvia': { uk: 'Латвія', ru: 'Латвия', en: 'Latvia' },
  'lebanon': { uk: 'Ліван', ru: 'Ливан', en: 'Lebanon' },
  'liberia': { uk: 'Ліберія', ru: 'Либерия', en: 'Liberia' },
  'lithuania': { uk: 'Литва', ru: 'Литва', en: 'Lithuania' },
  'luxembourg': { uk: 'Люксембург', ru: 'Люксембург', en: 'Luxembourg' },
  'malaysia': { uk: 'Малайзія', ru: 'Малайзия', en: 'Malaysia' },
  'mali': { uk: 'Малі', ru: 'Мали', en: 'Mali' },
  'malta': { uk: 'Мальта', ru: 'Мальта', en: 'Malta' },
  'mexico': { uk: 'Мексика', ru: 'Мексика', en: 'Mexico' },
  'moldova': { uk: 'Молдова', ru: 'Молдова', en: 'Moldova' },
  'monaco': { uk: 'Монако', ru: 'Монако', en: 'Monaco' },
  'montenegro': { uk: 'Чорногорія', ru: 'Черногория', en: 'Montenegro' },
  'morocco': { uk: 'Марокко', ru: 'Марокко', en: 'Morocco' },
  'netherlands': { uk: 'Нідерланди', ru: 'Нидерланды', en: 'Netherlands' },
  'niger': { uk: 'Нігер', ru: 'Нигер', en: 'Niger' },
  'nigeria': { uk: 'Нігерія', ru: 'Нигерия', en: 'Nigeria' },
  'north_macedonia': { uk: 'Північна Македонія', ru: 'Северная Македония', en: 'North Macedonia' },
  'norway': { uk: 'Норвегія', ru: 'Норвегия', en: 'Norway' },
  'panama': { uk: 'Панама', ru: 'Панама', en: 'Panama' },
  'peru': { uk: 'Перу', ru: 'Перу', en: 'Peru' },
  'poland': { uk: 'Польща', ru: 'Польша', en: 'Poland' },
  'portugal': { uk: 'Португалія', ru: 'Португалия', en: 'Portugal' },
  'qatar': { uk: 'Катар', ru: 'Катар', en: 'Qatar' },
  'romania': { uk: 'Румунія', ru: 'Румыния', en: 'Romania' },
  'rwanda': { uk: 'Руанда', ru: 'Руанда', en: 'Rwanda' },
  'saudi_arabia': { uk: 'Саудівська Аравія', ru: 'Саудовская Аравия', en: 'Saudi Arabia' },
  'senegal': { uk: 'Сенегал', ru: 'Сенегал', en: 'Senegal' },
  'serbia': { uk: 'Сербія', ru: 'Сербия', en: 'Serbia' },
  'sierra_leone': { uk: 'Сьєрра-Леоне', ru: 'Сьерра-Леоне', en: 'Sierra Leone' },
  'singapore': { uk: 'Сінгапур', ru: 'Сингапур', en: 'Singapore' },
  'slovakia': { uk: 'Словаччина', ru: 'Словакия', en: 'Slovakia' },
  'slovenia': { uk: 'Словенія', ru: 'Словения', en: 'Slovenia' },
  'somalia': { uk: 'Сомалі', ru: 'Сомали', en: 'Somalia' },
  'south_africa': { uk: 'Південно-Африканська Республіка', ru: 'Южно-Африканская Республика', en: 'South Africa' },
  'south_korea': { uk: 'Південна Корея', ru: 'Южная Корея', en: 'South Korea' },
  'spain': { uk: 'Іспанія', ru: 'Испания', en: 'Spain' },
  'sweden': { uk: 'Швеція', ru: 'Швеция', en: 'Sweden' },
  'switzerland': { uk: 'Швейцарія', ru: 'Швейцария', en: 'Switzerland' },
  'tajikistan': { uk: 'Таджикистан', ru: 'Таджикистан', en: 'Tajikistan' },
  'tanzania': { uk: 'Танзанія', ru: 'Танзания', en: 'Tanzania' },
  'thailand': { uk: 'Таїланд', ru: 'Таиланд', en: 'Thailand' },
  'togo': { uk: 'Того', ru: 'Того', en: 'Togo' },
  'turkey': { uk: 'Туреччина', ru: 'Турция', en: 'Turkey' },
  'uganda': { uk: 'Уганда', ru: 'Уганда', en: 'Uganda' },
  'ukraine': { uk: 'Україна', ru: 'Украина', en: 'Ukraine' },
  'united_arab_emirates': { uk: 'Об\'єднані Арабські Емірати', ru: 'Объединенные Арабские Эмираты', en: 'United Arab Emirates' },
  'united_kingdom': { uk: 'Велика Британія', ru: 'Великобритания', en: 'United Kingdom' },
  'united_states': { uk: 'Сполучені Штати', ru: 'Соединенные Штаты', en: 'United States' },
  'uzbekistan': { uk: 'Узбекистан', ru: 'Узбекистан', en: 'Uzbekistan' },
  'vietnam': { uk: 'В\'єтнам', ru: 'Вьетнам', en: 'Vietnam' },
  'zimbabwe': { uk: 'Зімбабве', ru: 'Зимбабве', en: 'Zimbabwe' },
};

export const CITY_NAMES: Record<string, Record<string, string>> = {
  'abidjan': { uk: 'Абіджан', ru: 'Абиджан', en: 'Abidjan' },
  'abu_dhabi': { uk: 'Абу-Дабі', ru: 'Абу-Даби', en: 'Abu Dhabi' },
  'abuja': { uk: 'Абуджа', ru: 'Абуджа', en: 'Abuja' },
  'accra': { uk: 'Аккра', ru: 'Аккра', en: 'Accra' },
  'addis_ababa': { uk: 'Аддіс-Абеба', ru: 'Аддис-Абеба', en: 'Addis Ababa' },
  'alanya': { uk: 'Аланія', ru: 'Аланья', en: 'Alanya' },
  'alexandria': { uk: 'Олександрія', ru: 'Александрия', en: 'Alexandria' },
  'alicante': { uk: 'Аліканте', ru: 'Аликанте', en: 'Alicante' },
  'almaty': { uk: 'Алма-Ата', ru: 'Алма-Ата', en: 'Almaty' },
  'amsterdam': { uk: 'Амстердам', ru: 'Амстердам', en: 'Amsterdam' },
  'ankara': { uk: 'Анкара', ru: 'Анкара', en: 'Ankara' },
  'ansan': { uk: 'Ансан', ru: 'Ансан', en: 'Ansan' },
  'antalya': { uk: 'Анталія', ru: 'Анталья', en: 'Antalya' },
  'antwerp': { uk: 'Антверпен', ru: 'Антверпен', en: 'Antwerp' },
  'astana': { uk: 'Астана', ru: 'Астана', en: 'Astana' },
  'athens': { uk: 'Афіни', ru: 'Афины', en: 'Athens' },
  'baku': { uk: 'Баку', ru: 'Баку', en: 'Baku' },
  'bali': { uk: 'Балі', ru: 'Бали', en: 'Bali' },
  'bamako': { uk: 'Бамако', ru: 'Бамако', en: 'Bamako' },
  'bangkok': { uk: 'Бангкок', ru: 'Бангкок', en: 'Bangkok' },
  'banjul': { uk: 'Банжул', ru: 'Банжул', en: 'Banjul' },
  'bar': { uk: 'Бар', ru: 'Бар', en: 'Bar' },
  'barcelona': { uk: 'Барселона', ru: 'Барселона', en: 'Barcelona' },
  'basel': { uk: 'Базель', ru: 'Базель', en: 'Basel' },
  'batumi': { uk: 'Батумі', ru: 'Батуми', en: 'Batumi' },
  'beijing': { uk: 'Пекін', ru: 'Пекин', en: 'Beijing' },
  'beirut': { uk: 'Бейрут', ru: 'Бейрут', en: 'Beirut' },
  'belek': { uk: 'Белек', ru: 'Белек', en: 'Belek' },
  'belgrade': { uk: 'Белград', ru: 'Белград', en: 'Belgrade' },
  'benidorm': { uk: 'Бенідорм', ru: 'Бенидорм', en: 'Benidorm' },
  'berlin': { uk: 'Берлін', ru: 'Берлин', en: 'Berlin' },
  'berne': { uk: 'Берн', ru: 'Берн', en: 'Bern' },
  'birmingham': { uk: 'Бірмінгем', ru: 'Бирмингем', en: 'Birmingham' },
  'bishkek': { uk: 'Бішкек', ru: 'Бишкек', en: 'Bishkek' },
  'bobo_dioulasso': { uk: 'Бобо-Діуласо', ru: 'Бобо-Диуласо', en: 'Bobo-Dioulasso' },
  'bodrum': { uk: 'Бодрум', ru: 'Бодрум', en: 'Bodrum' },
  'bogota': { uk: 'Богота', ru: 'Богота', en: 'Bogota' },
  'boston': { uk: 'Бостон', ru: 'Бостон', en: 'Boston' },
  'brasilia': { uk: 'Бразиліа', ru: 'Бразилиа', en: 'Brasilia' },
  'bratislava': { uk: 'Братислава', ru: 'Братислава', en: 'Bratislava' },
  'brazzaville': { uk: 'Браззавіль', ru: 'Браззавиль', en: 'Brazzaville' },
  'bremen': { uk: 'Бремен', ru: 'Бремен', en: 'Bremen' },
  'brno': { uk: 'Брно', ru: 'Брно', en: 'Brno' },
  'brussels': { uk: 'Брюссель', ru: 'Брюссель', en: 'Brussels' },
  'bucharest': { uk: 'Бухарест', ru: 'Бухарест', en: 'Bucharest' },
  'budapest': { uk: 'Будапешт', ru: 'Будапешт', en: 'Budapest' },
  'budva': { uk: 'Будва', ru: 'Будва', en: 'Budva' },
  'buenos_aires': { uk: 'Буенос-Айрес', ru: 'Буэнос-Айрес', en: 'Buenos Aires' },
  'burgas': { uk: 'Бургас', ru: 'Бургас', en: 'Burgas' },
  'bursa': { uk: 'Бурса', ru: 'Бурса', en: 'Bursa' },
  'cairo': { uk: 'Каїр', ru: 'Каир', en: 'Cairo' },
  'calgary': { uk: 'Калгарі', ru: 'Калгари', en: 'Calgary' },
  'cannes': { uk: 'Канни', ru: 'Канны', en: 'Cannes' },
  'casablanca': { uk: 'Касабланка', ru: 'Касабланка', en: 'Casablanca' },
  'cascais': { uk: 'Кашкайш', ru: 'Кашкайш', en: 'Cascais' },
  'catania': { uk: 'Катанія', ru: 'Катания', en: 'Catania' },
  'cherkasy': { uk: 'Черкаси', ru: 'Черкассы', en: 'Cherkasy' },
  'chernihiv': { uk: 'Чернігів', ru: 'Чернигов', en: 'Chernihiv' },
  'chernivtsi': { uk: 'Чернівці', ru: 'Черновцы', en: 'Chernivtsi' },
  'chicago': { uk: 'Чикаго', ru: 'Чикаго', en: 'Chicago' },
  'chisinau': { uk: 'Кишинів', ru: 'Кишинев', en: 'Chisinau' },
  'cologne': { uk: 'Кельн', ru: 'Кёльн', en: 'Cologne' },
  'conakry': { uk: 'Конакрі', ru: 'Конакри', en: 'Conakry' },
  'constant': { uk: 'Констанца', ru: 'Констанца', en: 'Constanta' },
  'copenhagen': { uk: 'Копенгаген', ru: 'Копенгаген', en: 'Copenhagen' },
  'cotonou': { uk: 'Котону', ru: 'Котону', en: 'Cotonou' },
  'dakar': { uk: 'Дакар', ru: 'Дакар', en: 'Dakar' },
  'danang': { uk: 'Дананг', ru: 'Дананг', en: 'Danang' },
  'dar_es_salaam': { uk: 'Дар-ес-Салам', ru: 'Дар-эс-Салам', en: 'Dar es Salaam' },
  'delhi': { uk: 'Делі', ru: 'Дели', en: 'Delhi' },
  'dnipro': { uk: 'Дніпро', ru: 'Днепр', en: 'Dnipro' },
  'doha': { uk: 'Доха', ru: 'Доха', en: 'Doha' },
  'dortmund': { uk: 'Дортмунд', ru: 'Дортмунд', en: 'Dortmund' },
  'douala': { uk: 'Дуала', ru: 'Дуала', en: 'Douala' },
  'dresden': { uk: 'Дрезден', ru: 'Дрезден', en: 'Dresden' },
  'dubai': { uk: 'Дубай', ru: 'Дубай', en: 'Dubai' },
  'dublin': { uk: 'Дублін', ru: 'Дублин', en: 'Dublin' },
  'dushanbe': { uk: 'Душанбе', ru: 'Душанбе', en: 'Dushanbe' },
  'dusseldorf': { uk: 'Дюссельдорф', ru: 'Дюссельдорф', en: 'Düsseldorf' },
  'edmonton': { uk: 'Едмонтон', ru: 'Эдмонтон', en: 'Edmonton' },
  'essen': { uk: 'Ессен', ru: 'Эссен', en: 'Essen' },
  'famagusta': { uk: 'Фамагуста', ru: 'Фамагуста', en: 'Famagusta' },
  'faro': { uk: 'Фару', ru: 'Фару', en: 'Faro' },
  'florence': { uk: 'Флоренція', ru: 'Флоренция', en: 'Florence' },
  'frankfurt_am_main': { uk: 'Франкфурт-на-Майні', ru: 'Франкфурт-на-Майне', en: 'Frankfurt am Main' },
  'freetown': { uk: 'Фрітаун', ru: 'Фритаун', en: 'Freetown' },
  'funchal': { uk: 'Фуншал', ru: 'Фуншал', en: 'Funchal' },
  'gazipasha': { uk: 'Газіпаша', ru: 'Газипаша', en: 'Gazipasha' },
  'gdansk': { uk: 'Гданськ', ru: 'Гданьск', en: 'Gdansk' },
  'geneva': { uk: 'Женева', ru: 'Женева', en: 'Geneva' },
  'guangzhou': { uk: 'Гуанчжоу', ru: 'Гуанчжоу', en: 'Guangzhou' },
  'guayaquil': { uk: 'Гуаякіль', ru: 'Гуаякиль', en: 'Guayaquil' },
  'haifa': { uk: 'Хайфа', ru: 'Хайфа', en: 'Haifa' },
  'haiphong': { uk: 'Хайфон', ru: 'Хайфон', en: 'Haiphong' },
  'hamburg': { uk: 'Гамбург', ru: 'Гамбург', en: 'Hamburg' },
  'hanoi': { uk: 'Ханой', ru: 'Ханой', en: 'Hanoi' },
  'hanover': { uk: 'Ганновер', ru: 'Ганновер', en: 'Hanover' },
  'harare': { uk: 'Хараре', ru: 'Хараре', en: 'Harare' },
  'harbin': { uk: 'Харбін', ru: 'Харбин', en: 'Harbin' },
  'helsinki': { uk: 'Гельсінкі', ru: 'Хельсинки', en: 'Helsinki' },
  'ho_chi_minh_city': { uk: 'Хошимін', ru: 'Хошимин', en: 'Ho Chi Minh City' },
  'hong_kong': { uk: 'Гонконг', ru: 'Гонконг', en: 'Hong Kong' },
  'houston': { uk: 'Х\'юстон', ru: 'Хьюстон', en: 'Houston' },
  'hurghada': { uk: 'Хургада', ru: 'Хургада', en: 'Hurghada' },
  'ibiza': { uk: 'Ібіца', ru: 'Ибица', en: 'Ibiza' },
  'incheon': { uk: 'Інчхон', ru: 'Инчхон', en: 'Incheon' },
  'istanbul': { uk: 'Стамбул', ru: 'Стамбул', en: 'Istanbul' },
  'ivano_frankivsk': { uk: 'Івано-Франківськ', ru: 'Ивано-Франковск', en: 'Ivano-Frankivsk' },
  'izmir': { uk: 'Ізмір', ru: 'Измир', en: 'Izmir' },
  'jeddah': { uk: 'Джидда', ru: 'Джедда', en: 'Jeddah' },
  'johannesburg': { uk: 'Йоганнесбург', ru: 'Йоханнесбург', en: 'Johannesburg' },
  'kamenskoe': { uk: 'Кам\'янське', ru: 'Каменское', en: 'Kamenskoe' },
  'kampala': { uk: 'Кампала', ru: 'Кампала', en: 'Kampala' },
  'kano': { uk: 'Кано', ru: 'Кано', en: 'Kano' },
  'karlovy_vary': { uk: 'Карлові Вари', ru: 'Карловы Вары', en: 'Karlovy Vary' },
  'kaunas': { uk: 'Каунас', ru: 'Каунас', en: 'Kaunas' },
  'kemer': { uk: 'Кемер', ru: 'Кемер', en: 'Kemer' },
  'kharkiv': { uk: 'Харків', ru: 'Харьков', en: 'Kharkiv' },
  'kherson': { uk: 'Херсон', ru: 'Херсон', en: 'Kherson' },
  'khmelnytskyi': { uk: 'Хмельницький', ru: 'Хмельницкий', en: 'Khmelnytskyi' },
  'kigali': { uk: 'Кігалі', ru: 'Кигали', en: 'Kigali' },
  'kinshasa': { uk: 'Кіншаса', ru: 'Киншаса', en: 'Kinshasa' },
  'koh_phangan': { uk: 'Пханган', ru: 'Пханган', en: 'Koh Phangan' },
  'koh_samui': { uk: 'Самуї', ru: 'Самуй', en: 'Koh Samui' },
  'kosice': { uk: 'Кошице', ru: 'Кошице', en: 'Kosice' },
  'kovel': { uk: 'Ковель', ru: 'Ковель', en: 'Kovel' },
  'krabi': { uk: 'Крабі', ru: 'Краби', en: 'Krabi' },
  'krakow': { uk: 'Краків', ru: 'Краков', en: 'Krakow' },
  'kramatorsk': { uk: 'Краматорськ', ru: 'Краматорск', en: 'Kramatorsk' },
  'kremenchuk': { uk: 'Кременчук', ru: 'Кременчуг', en: 'Kremenchuk' },
  'kropyvnytskyi': { uk: 'Кропивницький', ru: 'Кропивницкий', en: 'Kropyvnytskyi' },
  'kryvyi_rih': { uk: 'Кривий Ріг', ru: 'Кривой Рог', en: 'Kryvyi Rih' },
  'kuala_lumpur': { uk: 'Куала-Лумпур', ru: 'Куала-Лумпур', en: 'Kuala Lumpur' },
  'kumasi': { uk: 'Кумасі', ru: 'Кумаси', en: 'Kumasi' },
  'kyiv': { uk: 'Київ', ru: 'Киев', en: 'Kyiv' },
  'kyoto': { uk: 'Кіото', ru: 'Киото', en: 'Kyoto' },
  'kyrenia': { uk: 'Кіренія', ru: 'Кириния', en: 'Kyrenia' },
  'lagos': { uk: 'Лагос', ru: 'Лагос', en: 'Lagos' },
  'larnaca': { uk: 'Ларнака', ru: 'Ларнака', en: 'Larnaca' },
  'las_vegas': { uk: 'Лас-Вегас', ru: 'Лас-Вегас', en: 'Las Vegas' },
  'lausanne': { uk: 'Лозанна', ru: 'Лозанна', en: 'Lausanne' },
  'leipzig': { uk: 'Лейпциг', ru: 'Лейпциг', en: 'Leipzig' },
  'libreville': { uk: 'Лібревіль', ru: 'Либревиль', en: 'Libreville' },
  'lima': { uk: 'Ліма', ru: 'Лима', en: 'Lima' },
  'limassol': { uk: 'Лімасол', ru: 'Лимасол', en: 'Limassol' },
  'lisbon': { uk: 'Лісабон', ru: 'Лиссабон', en: 'Lisbon' },
  'liverpool': { uk: 'Ліверпуль', ru: 'Ливерпуль', en: 'Liverpool' },
  'ljubljana': { uk: 'Любляна', ru: 'Любляна', en: 'Ljubljana' },
  'lodz': { uk: 'Лодзь', ru: 'Лодзь', en: 'Lodz' },
  'lome': { uk: 'Ломе', ru: 'Ломе', en: 'Lomé' },
  'london': { uk: 'Лондон', ru: 'Лондон', en: 'London' },
  'los_angeles': { uk: 'Лос-Анджелес', ru: 'Лос-Анджелес', en: 'Los Angeles' },
  'luanda': { uk: 'Луанда', ru: 'Луанда', en: 'Luanda' },
  'lublin': { uk: 'Люблін', ru: 'Люблин', en: 'Lublin' },
  'lucerne': { uk: 'Люцерн', ru: 'Люцерн', en: 'Lucerne' },
  'lugano': { uk: 'Лугано', ru: 'Лугано', en: 'Lugano' },
  'lutsk': { uk: 'Луцьк', ru: 'Луцк', en: 'Lutsk' },
  'luxembourg': { uk: 'Люксембург', ru: 'Люксембург', en: 'Luxembourg' },
  'lviv': { uk: 'Львів', ru: 'Львов', en: 'Lviv' },
  'lyon': { uk: 'Ліон', ru: 'Лион', en: 'Lyon' },
  'madrid': { uk: 'Мадрид', ru: 'Мадрид', en: 'Madrid' },
  'malaga': { uk: 'Малага', ru: 'Малага', en: 'Malaga' },
  'mallorca': { uk: 'Майорка', ru: 'Майорка', en: 'Mallorca' },
  'manama': { uk: 'Манама', ru: 'Манама', en: 'Manama' },
  'manchester': { uk: 'Манчестер', ru: 'Манчестер', en: 'Manchester' },
  'marbella': { uk: 'Марбелья', ru: 'Марбелья', en: 'Marbella' },
  'marijampole': { uk: 'Маріямполе', ru: 'Мариямполе', en: 'Marijampolė' },
  'marseille': { uk: 'Марсель', ru: 'Марсель', en: 'Marseille' },
  'medellin': { uk: 'Медельїн', ru: 'Медельин', en: 'Medellín' },
  'mersin': { uk: 'Мерсін', ru: 'Мерсин', en: 'Mersin' },
  'mexico_city': { uk: 'Мехіко', ru: 'Мехико', en: 'Mexico City' },
  'miami': { uk: 'Маямі', ru: 'Майами', en: 'Miami' },
  'milan': { uk: 'Мілан', ru: 'Милан', en: 'Milan' },
  'mogadishu': { uk: 'Могадішо', ru: 'Могадишо', en: 'Mogadishu' },
  'mombasa': { uk: 'Момбаса', ru: 'Момбаса', en: 'Mombasa' },
  'monaco': { uk: 'Монако', ru: 'Монако', en: 'Monaco' },
  'monrovia': { uk: 'Монровія', ru: 'Монровия', en: 'Monrovia' },
  'montreal': { uk: 'Монреаль', ru: 'Монреаль', en: 'Montreal' },
  'montreux': { uk: 'Монтрьо', ru: 'Монтрё', en: 'Montreux' },
  'mukachevo': { uk: 'Мукачево', ru: 'Мукачево', en: 'Mukachevo' },
  'mumbai': { uk: 'Мумбай', ru: 'Мумбай', en: 'Mumbai' },
  'munich': { uk: 'Мюнхен', ru: 'Мюнхен', en: 'Munich' },
  'murcia': { uk: 'Мурсія', ru: 'Мурсия', en: 'Murcia' },
  'mykolaiv': { uk: 'Миколаїв', ru: 'Николаев', en: 'Mykolaiv' },
  'nairobi': { uk: 'Найробі', ru: 'Найроби', en: 'Nairobi' },
  'nanjing': { uk: 'Нанкін', ru: 'Нанкин', en: 'Nanjing' },
  'naples': { uk: 'Неаполь', ru: 'Неаполь', en: 'Naples' },
  'new_york': { uk: 'Нью-Йорк', ru: 'Нью-Йорк', en: 'New York' },
  'nha_trang': { uk: 'Нячанг', ru: 'Нячанг', en: 'Nha Trang' },
  'niamey': { uk: 'Ніамей', ru: 'Ниамей', en: 'Niamey' },
  'nice': { uk: 'Ніцца', ru: 'Ницца', en: 'Nice' },
  'nicosia': { uk: 'Нікосія', ru: 'Никосия', en: 'Nicosia' },
  'nicosia_northern_cyprus': { uk: 'Нікосія (Північний Кіпр)', ru: 'Никосия (Северный Кипр)', en: 'Nicosia (Northern Cyprus)' },
  'nis': { uk: 'Ніш', ru: 'Ниш', en: 'Niš' },
  'novi_sad': { uk: 'Нові-Сад', ru: 'Нови-Сад', en: 'Novi Sad' },
  'nuremberg': { uk: 'Нюрнберг', ru: 'Нюрнберг', en: 'Nuremberg' },
  'odesa': { uk: 'Одеса', ru: 'Одесса', en: 'Odesa' },
  'onne': { uk: 'Онне', ru: 'Онне', en: 'Onne' },
  'orlando': { uk: 'Орландо', ru: 'Орландо', en: 'Orlando' },
  'osaka': { uk: 'Осака', ru: 'Осака', en: 'Osaka' },
  'oslo': { uk: 'Осло', ru: 'Осло', en: 'Oslo' },
  'ottawa': { uk: 'Оттава', ru: 'Оттава', en: 'Ottawa' },
  'ouagadougou': { uk: 'Уагадугу', ru: 'Уагадугу', en: 'Ouagadougou' },
  'palermo': { uk: 'Палермо', ru: 'Палермо', en: 'Palermo' },
  'panama': { uk: 'Панама', ru: 'Панама', en: 'Panama' },
  'panevezys': { uk: 'Паневежис', ru: 'Паневежис', en: 'Panevėžys' },
  'paphos': { uk: 'Пафос', ru: 'Пафос', en: 'Paphos' },
  'paris': { uk: 'Париж', ru: 'Париж', en: 'Paris' },
  'parma': { uk: 'Парма', ru: 'Парма', en: 'Parma' },
  'pattaya': { uk: 'Паттая', ru: 'Паттайя', en: 'Pattaya' },
  'philadelphia': { uk: 'Філадельфія', ru: 'Филадельфия', en: 'Philadelphia' },
  'phuket': { uk: 'Пхукет', ru: 'Пхукет', en: 'Phuket' },
  'podgorica': { uk: 'Подгориця', ru: 'Подгорица', en: 'Podgorica' },
  'poltava': { uk: 'Полтава', ru: 'Полтава', en: 'Poltava' },
  'porto': { uk: 'Порту', ru: 'Порту', en: 'Porto' },
  'poznan': { uk: 'Познань', ru: 'Познань', en: 'Poznań' },
  'prague': { uk: 'Прага', ru: 'Прага', en: 'Prague' },
  'przemysl': { uk: 'Перемишль', ru: 'Пшемысль', en: 'Przemyśl' },
  'quebec': { uk: 'Квебек', ru: 'Квебек', en: 'Quebec' },
  'quito': { uk: 'Кіто', ru: 'Кито', en: 'Quito' },
  'ras_al_khaimah': { uk: 'Рас-ель-Хайма', ru: 'Рас-эль-Хайма', en: 'Ras Al Khaimah' },
  'riga': { uk: 'Рига', ru: 'Рига', en: 'Riga' },
  'rimini': { uk: 'Ріміні', ru: 'Римини', en: 'Rimini' },
  'rio_de_janeiro': { uk: 'Ріо-де-Жанейро', ru: 'Рио-де-Жанейро', en: 'Rio de Janeiro' },
  'rivne': { uk: 'Рівне', ru: 'Ровно', en: 'Rivne' },
  'rome': { uk: 'Рим', ru: 'Рим', en: 'Rome' },
  'rotterdam': { uk: 'Роттердам', ru: 'Роттердам', en: 'Rotterdam' },
  'rustavi': { uk: 'Руставі', ru: 'Рустави', en: 'Rustavi' },
  'rzeszow': { uk: 'Жешув', ru: 'Жешув', en: 'Rzeszow' },
  'sambir': { uk: 'Самбір', ru: 'Самбор', en: 'Sambir' },
  'samsun': { uk: 'Самсун', ru: 'Самсун', en: 'Samsun' },
  'san_francisco': { uk: 'Сан-Франциско', ru: 'Сан-Франциско', en: 'San Francisco' },
  'san_jose': { uk: 'Сан-Хосе', ru: 'Сан-Хосе', en: 'San José' },
  'santiago': { uk: 'Сантьяго', ru: 'Сантьяго', en: 'Santiago' },
  'santo_domingo': { uk: 'Санто-Домінго', ru: 'Санто-Доминго', en: 'Santo Domingo' },
  'sao_paulo': { uk: 'Сан-Паулу', ru: 'Сан-Паулу', en: 'São Paulo' },
  'seattle': { uk: 'Сіетл', ru: 'Сиэтл', en: 'Seattle' },
  'seoul': { uk: 'Сеул', ru: 'Сеул', en: 'Seoul' },
  'seville': { uk: 'Севілья', ru: 'Севилья', en: 'Seville' },
  'shanghai': { uk: 'Шанхай', ru: 'Шанхай', en: 'Shanghai' },
  'sharjah': { uk: 'Шарджа', ru: 'Шарджа', en: 'Sharjah' },
  'sharm_el_sheikh': { uk: 'Шарм-еш-Шейх', ru: 'Шарм-эш-Шейх', en: 'Sharm El Sheikh' },
  'shenzhen': { uk: 'Шеньчжень', ru: 'Шэньчжэнь', en: 'Shenzhen' },
  'shymkent': { uk: 'Шимкент', ru: 'Шымкент', en: 'Shymkent' },
  'singapore': { uk: 'Сінгапур', ru: 'Сингапур', en: 'Singapore' },
  'skopje': { uk: 'Скоп\'є', ru: 'Скопье', en: 'Skopje' },
  'sofia': { uk: 'Софія', ru: 'София', en: 'Sofia' },
  'stockholm': { uk: 'Стокгольм', ru: 'Стокгольм', en: 'Stockholm' },
  'stuttgart': { uk: 'Штутгарт', ru: 'Штутгарт', en: 'Stuttgart' },
  'sumy': { uk: 'Суми', ru: 'Сумы', en: 'Sumy' },
  'sydney': { uk: 'Сідней', ru: 'Сидней', en: 'Sydney' },
  'szczecin': { uk: 'Щецин', ru: 'Щецин', en: 'Szczecin' },
  'tallinn': { uk: 'Таллінн', ru: 'Таллин', en: 'Tallinn' },
  'tashkent': { uk: 'Ташкент', ru: 'Ташкент', en: 'Tashkent' },
  'tbilisi': { uk: 'Тбілісі', ru: 'Тбилиси', en: 'Tbilisi' },
  'tel_aviv': { uk: 'Тель-Авів', ru: 'Тель-Авив', en: 'Tel Aviv' },
  'tema': { uk: 'Тема', ru: 'Тема', en: 'Tema' },
  'tenerife': { uk: 'Тенерифе', ru: 'Тенерифе', en: 'Tenerife' },
  'ternopil': { uk: 'Тернопіль', ru: 'Тернополь', en: 'Ternopil' },
  'thessaloniki': { uk: 'Салоніки', ru: 'Салоники', en: 'Thessaloniki' },
  'tianjin': { uk: 'Тяньцзінь', ru: 'Тяньцзинь', en: 'Tianjin' },
  'tirana': { uk: 'Тірана', ru: 'Тирана', en: 'Tirana' },
  'tivat': { uk: 'Тіват', ru: 'Тиват', en: 'Tivat' },
  'tokyo': { uk: 'Токіо', ru: 'Токио', en: 'Tokyo' },
  'toronto': { uk: 'Торонто', ru: 'Торонто', en: 'Toronto' },
  'toyama': { uk: 'Тояма', ru: 'Тояма', en: 'Toyama' },
  'utrecht': { uk: 'Утрехт', ru: 'Утрехт', en: 'Utrecht' },
  'uzhhorod': { uk: 'Ужгород', ru: 'Ужгород', en: 'Uzhhorod' },
  'valencia': { uk: 'Валенсія', ru: 'Валенсия', en: 'Valencia' },
  'valletta': { uk: 'Валлетта', ru: 'Валлетта', en: 'Valletta' },
  'vancouver': { uk: 'Ванкувер', ru: 'Ванкувер', en: 'Vancouver' },
  'varna': { uk: 'Варна', ru: 'Варна', en: 'Varna' },
  'vienna': { uk: 'Відень', ru: 'Вена', en: 'Vienna' },
  'vilnius': { uk: 'Вільнюс', ru: 'Вильнюс', en: 'Vilnius' },
  'vinnytsia': { uk: 'Вінниця', ru: 'Винница', en: 'Vinnytsia' },
  'warsaw': { uk: 'Варшава', ru: 'Варшава', en: 'Warsaw' },
  'washington': { uk: 'Вашингтон', ru: 'Вашингтон', en: 'Washington' },
  'wroclaw': { uk: 'Вроцлав', ru: 'Вроцлав', en: 'Wroclaw' },
  'yaounde': { uk: 'Яунде', ru: 'Яунде', en: 'Yaoundé' },
  'yerevan': { uk: 'Єреван', ru: 'Ереван', en: 'Yerevan' },
  'zagreb': { uk: 'Загреб', ru: 'Загреб', en: 'Zagreb' },
  'zaporizhzhia': { uk: 'Запоріжжя', ru: 'Запорожье', en: 'Zaporizhzhia' },
  'zaragoza': { uk: 'Сарагоса', ru: 'Сарагоса', en: 'Zaragoza' },
  'zhytomyr': { uk: 'Житомир', ru: 'Житомир', en: 'Zhytomyr' },
  'zurich': { uk: 'Цюрих', ru: 'Цюрих', en: 'Zurich' },
};

export function getCountryName(url: string, locale: string): string {
  return COUNTRY_NAMES[url]?.[locale] || COUNTRY_NAMES[url]?.en || url;
}

export function getCityName(url: string, locale: string): string {
  return CITY_NAMES[url]?.[locale] || CITY_NAMES[url]?.en || url;
}
